print("=== Анализ последовательности ДНК ===\n")
dna_user = str(input("Введите последовательность ДНК:\n"))
dna_p = str.upper(dna_user)
a = dna_p.count("A")
t = dna_p.count("T")
g = dna_p.count("G")
c = dna_p.count("C")
print(f"Последовательность в верхнем регистре: {dna_p}\n")
print(f"Подсчёт нуклеотидов:\nA: {a}\nT: {t}\nG: {g} \nC: {c}\n Общая длина: {len(dna_p)} нуклеотидов")
